# Site settings

title:          Blogs
url:            "https://nicebowl.fun/"


# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         UID0
  # url:          https://chester.how
  email:        UID-0000000@gmail.com


# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks 设置页数
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale